#!/bin/bash
# Auto-commit script — generated by auto-git-commit skill
# Commits and pushes all changes with a timestamp message

REPO_DIR="$(git rev-parse --show-toplevel 2>/dev/null)"

if [ -z "$REPO_DIR" ]; then
  echo "[auto-commit] ERROR: Not inside a git repo. Exiting."
  exit 1
fi

cd "$REPO_DIR" || exit 1

# Check for changes
if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  echo "[auto-commit] $(date '+%Y-%m-%d %H:%M:%S') — No changes. Skipping."
  exit 0
fi

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
BRANCH=$(git branch --show-current)

git add -A
git commit -m "auto-commit: $TIMESTAMP"
git push origin "$BRANCH"

echo "[auto-commit] $TIMESTAMP — Committed and pushed to $BRANCH."
