#!/bin/bash
# Auto-commit loop — runs every 15 minutes in the background
# Generated by auto-git-commit skill

REPO_DIR="/home/user/Youtube"
LOG_FILE="$REPO_DIR/auto_commit.log"

while true; do
  cd "$REPO_DIR" || exit 1

  if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
    echo "[auto-commit] $(date '+%Y-%m-%d %H:%M:%S') — No changes. Skipping." >> "$LOG_FILE"
  else
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    BRANCH=$(git branch --show-current)
    git add -A
    git commit -m "auto-commit: $TIMESTAMP" >> "$LOG_FILE" 2>&1
    git push origin "$BRANCH" >> "$LOG_FILE" 2>&1
    echo "[auto-commit] $TIMESTAMP — Committed and pushed to $BRANCH." >> "$LOG_FILE"
  fi

  sleep 900
done
